clone_folder: c:\gopath\src\github.com\vibhavp\rcon_client

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - GOARCH=386 go build -v -o rcon_client_x86.exe
  - GOARCH=amd64 go build -v -o rcon_client_x86_64.exe

artifacts:
  - path: rcon_client